---
#                  _  __          __     ___            _        
#  _ __   ___ _ __| |/ /__ _ __ __\ \   / / |_ __ _ ___| | _____ 
# | '_ \ / _ \ '__| | / __| '__/ __| | / /| __/ _` / __| |/ / __|
# | |_) |  __/ |  | | \__ \ | | (__| |/ / | || (_| \__ \   <\__ \
# | .__/ \___|_|  |_| |___/_|  \___| /_/   \__\__,_|___/_|\_\___/
# |_|                \_\          /_/                            
# get-archive
- name: get-archive | perl-{{ perl.version }}.tar.gz should be downloded at {{ perl.workingdir }}
  get_url:
    url:  "http://www.cpan.org/src/5.0/perl-{{ perl.version }}.tar.gz"
    dest: "{{ perl.workingdir }}/perl-{{ perl.version }}.tar.gz"

- name: get-archive | {{ perl.workingdir }}/perl-{{ perl.version }}.tar.gz should be extracted
  unarchive:
    src:     "{{ perl.workingdir }}/perl-{{ perl.version }}.tar.gz"
    dest:    "{{ perl.workingdir }}"
    creates: "{{ perl.workingdir }}/perl-{{ perl.version }}"
    copy:    "no"

